apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: hello
data:
  WELCOME_MESSAGE: "Hello from ConfigMap!"
  index.html: |
    <html>
      <body style="font-family:sans-serif; text-align:center;">
        <h1>Hello from Nginx Pod!</h1>
        <p>This page is served from a file in a ConfigMap 🎉</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-container
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WELCOME_MESSAGE
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-volume
          configMap:
            name: app-config
            items:
              - key: index.html
                path: index.html
---
